# Generated by Django 5.2.17 on 2026-09-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('changed_modules', models.JSONField(default=list)),
                ('open_critical_defects', models.JSONField(default=list)),
                ('declared_fixes', models.JSONField(default=list)),
                ('code_revision', models.CharField(default='lab-v1', max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('bug_ids', models.JSONField(default=list)),
                ('revision', models.CharField(default='scenario-v1', max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DataPreparationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('seed', models.PositiveIntegerField()),
                ('base_date', models.DateField()),
                ('raw_rows', models.PositiveIntegerField()),
                ('treated_rows', models.PositiveIntegerField()),
                ('issues', models.JSONField(default=dict)),
                ('transformations', models.JSONField(default=list)),
                ('decision_note', models.CharField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('coverage_threshold', models.FloatField(default=80.0)),
                ('risk_threshold', models.FloatField(default=0.8)),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('rule_results', models.JSONField(default=list)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.candidate')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.gateconfig')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True)),
                ('data_decision', models.TextField(blank=True)),
                ('priority', models.TextField(blank=True)),
                ('visualization', models.TextField(blank=True)),
                ('release_decision', models.TextField(blank=True)),
                ('ai_tool', models.CharField(blank=True, max_length=120)),
                ('human_checks', models.TextField(blank=True)),
                ('checklist', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.candidate')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.gateevaluation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.scenario'),
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('code_revision', models.CharField(max_length=40)),
                ('case_revisions', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('running', 'Em execucao'), ('completed', 'Concluida'), ('error', 'Erro do executor')], default='waiting', max_length=20)),
                ('results', models.JSONField(default=list)),
                ('coverage_lines', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage_considered', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage_percent', models.FloatField(blank=True, null=True)),
                ('coverage_scope', models.CharField(default='loja.domain, loja.services', max_length=120)),
                ('scope_kind', models.CharField(default='selection', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('artifact_dir', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.candidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLabState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.candidate')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorio.scenario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('model_version', models.CharField(max_length=40)),
                ('features', models.JSONField(default=dict)),
                ('score', models.FloatField()),
                ('explanation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='laboratorio.candidate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'module', 'model_version'), name='unique_candidate_prediction')],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=60)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('requirement_id', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=240)),
                ('scenario_type', models.CharField(max_length=30)),
                ('operation', models.CharField(max_length=40)),
                ('inputs', models.JSONField(default=dict)),
                ('expected', models.JSONField(default=dict)),
                ('mandatory', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['identifier'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'identifier'), name='unique_test_identifier_per_owner')],
            },
        ),
    ]
