# Generated by Django 5.2.17 on 2026-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='scenario_revision',
            field=models.CharField(default='scenario-v1', max_length=30),
        ),
    ]
